export const DB_TABLE_NAMES = {
  attendance: 'attendance',
  bank: 'bank',
  customer: 'customer',
  externalParty: 'external_party',
  externalProject: 'external_project',
  leave: 'leave',
  payroll: 'payroll',
  project: 'project',
  purchase: 'purchase',
  reimburse: 'reimburse',
  schedule: 'schedule',
  shiftApplication: 'shift_application',
  system: 'system',
  task: 'task',
  user: 'user',
  userCustomer: 'user_customer',
  userDetail: 'user_detail',
  userTask: 'user_task',
  transaction: 'transaction',
};
