export enum TaskStatus {
  PENDING = 'PENDING',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  ABANDONED = 'ABANDONED',
}

export enum TaskVisibleTo {
  ALL = 'ALL',
  INVISIBLE = 'INVISIBLE',
  DEPARTMENT = 'DEPARTMENT',
  ASSIGNEE = 'ASSIGNEE',
}
